### PR TITLE
set attribute values for snapshotting input values

### PR DESCRIPTION
**Pull request by cbroeren**
Fix for snapshotting input values, issue #6.
Not sure this is the best way to do this

### CODE REVIEW

**Comment by cbroeren** [comment]
You're absolutely right. Missing a lot of cases. Will improve it before the end of the week.

**Comment by fotinakis** [comment]
Hey @cbroeren, have any time to finish this out? No worries if not, just checking—thinking about dedicating some time to fix this.

**Comment by cbroeren** [comment]
@fotinakis, No I'm sorry, I started it, but I'm much busier then expected. Excuse me for not fulfilling my promise. For me it will take a while to make time for this. Would be nice when it will be fixed though, will really appreciate it.

**Comment by kiwiupover** [comment]
@fotinakis FYI I added a PR to ember-svg-jar https://github.com/ivanvotti/ember-svg-jar/pull/33 

When embedding svgs in the document they are put into the body of the document by default. My PR allows the user to move the injected object inside the `#ember-testing-container`. 

Will this PR change the percy snapshot root element from `#ember-test` -> `#ember-testing-container` ? 

As I type master is using `#ember-test`

Cheers
Dave

PS have you had post-it notes in your salad lately?

**Comment by fotinakis** [comment]
@kiwiupover This PR will not affect that, no. :) I've commented on your SVG PR, that would definitely fix the issue you were having. We should create a separate ember-percy issue for adding a `onSnapshot` hook that can modify the DOM.

**Comment by bennettmt** [comment]
@cbroeren @fotinakis I have some updates to this PR that I would like to commit that addresses some of the requested changes.  What is the best way to do so?

**Comment by fotinakis** [comment]
Hey @bennettmt — cool! This PR is pretty out of date at this point, though the idea is still solid. Can you just create another PR?

**Comment by fotinakis** [comment]
Going to close this one as it's gotten stale, but leaving #6 open.

**Pull request closed without merging**
